
# A string used to distinguish different Supabase projects on the same host. Defaults to the
# working directory name when running `supabase init`.
project_id = "oiurdrlibohoaruehrzz"
# [api]
# port = 54321

# [db]
# port = 54322

# [studio]
# port = 54323

# [inbucket]
# port = 54324

# [auth]
# site_url = "http://localhost:3000"
# additional_redirect_urls = ["https://localhost:3000"]
# jwt_expiry = 3600
# enable_refresh_token_rotation = true
# refresh_token_reuse_interval = 10
# enable_signup = true

# [defaults.metadata]
# functions_access_control = false

[functions.create_test_ride]
verify_jwt = false

