
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oiurdrlibohoaruehrzz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9pdXJkcmxpYm9ob2FydWVocnp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0OTE3MjEsImV4cCI6MjA1OTA2NzcyMX0.Cr2Tum3zzUXolmLZGGbUeGD014YYm1WC2VXr__US5JI";

// Configure the Supabase client with explicit settings for auth persistence
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true
    }
  }
);
